benzinga/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('web_api.urls', namespace='web_api'))
]

web_api/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^transaction/', views.trans, name='transaction'),
    url(r'^sell/$', views.trans, name='transaction'),
    url(r'^thanks/$', views.thanks, name='thanks'),
    url(r'^whoops/$', views.whoops, name='whoops'),
]

web_api/models.py
from django.db import models

# Create your models here.

web_api/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse

import urllib2
import json
# Create your views here.


def home(request):
    context = {}

    if 'portfolio' in request.session:
        value = request.session["portfolio"]
    else:
        request.session['portfolio'] = 100000
        value = request.session['portfolio']
    context['current_value'] = value

    if 'purchased' in request.session:
        pass
    else:
        request.session['purchased'] = []

    if request.method == 'POST':
        symbol = request.POST['symbol'].upper()
        api_endpint = 'http://careers-data.benzinga.com/rest/richquote?symbols=%s' \
                      % symbol
        req = urllib2.urlopen(api_endpint)
        data = json.load(req)
        if 'error' in data[symbol]:
            return HttpResponseRedirect(reverse('web_api:whoops'))
        bidprice = data[symbol]['bidPrice']
        context['bidprice'] = bidprice
        askprice = data[symbol]['askPrice']
        context['askprice'] = askprice
        context['symbol'] = symbol
        request.session['symbol'] = symbol
        request.session['bidprice'] = bidprice
        request.session['askprice'] = askprice
    context['purchased'] = request.session['purchased']
    return render(request, 'base.html', context)


def trans(request):
    context = {}

    if 'portfolio' in request.session:
        value = request.session["portfolio"]
    else:
        request.session['portfolio'] = 100000
        value = request.session['portfolio']

    if request.method == 'POST':
        purchased = request.session['purchased']
        quantity = request.POST['quantity']
        ask_price = request.session['askprice']
        if 'buy' in request.POST:
            symbol = request.session['symbol']
            switch = False

            for i in range(len(purchased)):
                if symbol == purchased[i][0]:
                    holder = purchased[i]
                    purchased[i] = (holder[0], (int(holder[1]) + int(quantity)), ask_price)
                    switch = True
            if switch is False:
                purchased.append((symbol, quantity, ask_price))

            cost = int(quantity) * int(ask_price)
            free_funds = value - cost
            context['current_value'] = free_funds
            request.session['portfolio'] = free_funds

        elif 'sell' in request.POST:
            symbol = request.POST['symbol']
            for i in range(len(purchased)):
                if symbol == purchased[i][0]:
                    holder = purchased[i]
                    purchased[i] = (holder[0], (int(holder[1]) - int(quantity)), ask_price)

            cost = int(quantity) * int(ask_price)
            free_funds = value + cost
            context['current_value'] = free_funds
            request.session['portfolio'] = free_funds

        request.session['purchased'] = purchased
        context['purchased'] = purchased
        return HttpResponseRedirect(reverse('web_api:thanks'))


def thanks(request):
    return render(request, 'thanks.html')

def whoops(request):
    return render(request, 'whoops.html')

benzinga/templates/base.html
<!DOCTYPE html>

<html>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static "css/benzinga.css" %}" />

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js">
</script>
<script type="text/javascript">
function validateForm() {
    var x = document.forms["purchase"]["quantity"].value;
    var y = document.getElementById("bidprice").innerHTML;
    var z = document.getElementById("cv").innerHTML;
    var total = x * y;
    if (  total > z ) {
        alert("Insufficent funds");
        return false;
    }
}
function validateForm2() {
    var x = document.forms["sell"]["quantity"].value;
    console.log(x)
    var y = document.getElementById("owned_quant").innerHTML;
    console.log(y)
    if (  x > y ) {
        alert("Insufficent Shares");
        return false;
    }
}
</script>
<form id='form1' method="POST" action='.'>
    {% csrf_token %}
    <div id='symbol'>
    <input type="text" name=symbol placeholder='Symbol'>
    <input type="submit" value="Search">
    </div>
</form>

<p>Your Balance</p>
<p id='cv'>{{current_value}}</p>


{% if askprice %}
<p>prices for stock: {{symbol}}</p>
<table style="width:100%">
  <tr>
    <th>Bid</th>
    <th>Ask</th>
  </tr>
  <tr>
    <td id='bidprice'>{{bidprice}}</td>
    <td>{{askprice}}</td>
  </tr>
</table>
<form name='purchase' method="POST" action='transaction/' onsubmit="return validateForm()">
    {% csrf_token %}
    <div id='buyorsell'>
    <input type="text" name=quantity placeholder='Quantity'>
    <input type="submit" name=buy value="buy">
    </div>
</form>

{% endif %}

<h3>Your Portfolio</h3>
<table style="width:100%">
  <tr>
    <th>Symbol</th>
    <th>Shares</th>
    <th>Cost</th>
    <th>Sell Shares</th>
  </tr>
  {% for item in purchased %}
  <tr>
    <td>{{item.0}}</td>
    <td id='owned_quant'>{{item.1}}</td>
    <td>{{item.2}}</td>
    <td>
    <form name='sell' method="POST" action='sell/' onsubmit="return validateForm2()">
    {% csrf_token %}
    <input  type="text" name=quantity placeholder='Quantity'>
    <input type="hidden" name=symbol value={{item.0}}>
    <input type="submit" name=sell value="Sell">
    </form>
    </td>
  </tr>
    {% endfor %}
</table>


</html>

benzinga/templates/thanks.html
<!DOCTYPE html>

<html>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static "css/benzinga.css" %}" />

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js">
</script>

<h3> Thank you for the transaction </h3>

<a href="{% url 'web_api:home' %}"> Back to Home </a>

</html>

benzinga/templates/whoops.html
<!DOCTYPE html>

<html>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static "css/benzinga.css" %}" />

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js">
</script>

<h3> Could not find that stock symbol - try another</h3>

<a href="{% url 'web_api:home' %}"> Back to Home </a>

</html>